### ISSUE TITLE
Tokenize begins with full stop.

### ISSUE THREAD

**Issue by haampie** [JuliaText/WordTokenizers.jl#28]
```julia
tokenize("hello world.")
3-element Array{String,1}:
 "."    
 "hello"
 "world"
```

Shouldn't this return `["hello", "world", "."]`?

**Comment by oxinabox** [comment]
Hmm how did the tests miss this?
Bug is in https://github.com/JuliaText/WordTokenizers.jl/blob/master/src/words/TokTok.jl#L118
(And again later in that function)
That function should not flush.
It should return the final character(s).
To be flushed at the end.

PR would be appreciated
